import {useRef,useState} from 'react';
import CorpusGraph from './CorpusGraph';
import type {Evidence,QueryResponse} from './api';
const tabs=['Knowledge Graph','Sources','Verification'] as const;
type Tab=typeof tabs[number];
// Only direct graph provenance exposes a directed, typed pair. Never infer
// relationships from prose, source names, selection reasons, or hybrid scores.
export function graphEvidence(evidence:Evidence[]):Evidence[]{
 return evidence.filter(e=>typeof e.relationship_type==='string' && e.relationship_type.trim() && Array.isArray(e.entity_path) && e.entity_path.length===2 && e.entity_path.every(n=>typeof n==='string' && n.trim()));
}
export default function AnswerInspector({response,question,pending=false}:{response?:QueryResponse;question?:string;pending?:boolean}){
 const [tab,setTab]=useState<Tab>('Verification');const buttons=useRef<(HTMLButtonElement|null)[]>([]);
 function move(event:React.KeyboardEvent,index:number){let next=index;if(event.key==='ArrowRight')next=(index+1)%tabs.length;else if(event.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else return;event.preventDefault();setTab(tabs[next]);buttons.current[next]?.focus();}
 const edges=response?graphEvidence(response.provenance):[];
 const trace=response?.execution_trace;
 return <aside className="answer-inspector" aria-label="Answer Inspector"><div className="inspector-heading"><span className="eyebrow">GROUNDING & VERIFICATION</span><h2>Answer Inspector</h2><p>{question || 'Ask a question to inspect its evidence.'}</p>{pending && <p role="status">Waiting for this response. No verification result is available yet.</p>}</div>
 <div role="tablist" aria-label="Inspector views" className="inspector-tabs">{tabs.map((name,i)=><button key={name} ref={node=>{buttons.current[i]=node;}} role="tab" id={`inspector-tab-${i}`} aria-selected={tab===name} aria-controls={`inspector-panel-${i}`} tabIndex={tab===name?0:-1} onClick={()=>setTab(name)} onKeyDown={e=>move(e,i)}>{name}</button>)}</div>
 <div role="tabpanel" tabIndex={0} id={`inspector-panel-${tabs.indexOf(tab)}`} aria-labelledby={`inspector-tab-${tabs.indexOf(tab)}`} className="inspector-panel">
 {tab==='Verification' && <><h3>Evidence decision</h3>{response?<><dl className="verification-fields"><dt>Evidence sufficient</dt><dd>{String(response.evidence_sufficient)}</dd><dt>Backend grounding status</dt><dd>{response.grounding_status}</dd><dt>Selected route</dt><dd>{response.selected_retrieval_route ?? 'Not provided'}</dd></dl><p>{response.sufficiency_reason}</p></>:<p className="unavailable">{pending?'Pending API response':'Not evaluated — no active response'}</p>}<p className="inspector-note">Evidence sufficiency evaluates support for the question. It is not claim-by-claim verification of the final answer.</p>
 <h3>Post-generation claim verification</h3>{response?.verification?<><p>API status: {response.verification.status}</p><p className="inspector-note">{response.verification.limitation}</p><p>Coverage complete: {String(response.verification.coverage_complete)} · Blocked: {String(response.verification.blocked)}</p>{response.verification.claims.map((c,i)=><details key={i} className="inspector-source"><summary>{c.status} · {c.critical?'Critical claim':'Claim'}</summary><p className="verbatim">{c.text}</p><p>Rule: {c.reason_code}</p><p>Evidence: {c.evidence_ids.join(', ') || 'None'}</p></details>)}</>:<><p className="unavailable">Not implemented / not evaluated</p><p>No generated-claim audit or entailment result is provided by this API response.</p></>}
 <h3>Numeric / date consistency</h3><p className="unavailable">{response?.verification?'Limited to literal and same-template values; other values NOT_VERIFIED':'Not implemented / not evaluated'}</p><p>No general numeric/date inference or unit conversion is performed.</p>
 <h3>Human review</h3>{response?.review?<><p className="unavailable">{response.review.status}</p><p>{response.review.limitation}</p></>:<p className="unavailable">Unavailable — no approval workflow</p>}<p>High-risk decisions need independent human review. This demo neither requests nor records approval.</p>
 <details className="trace-details"><summary>API execution trace</summary>{trace && typeof trace.interpreted_intent==='string'?<><p>Intent: {trace.interpreted_intent}</p><p>Generation mode: {trace.final_generation_mode ?? 'Not provided'}</p><p>Retrieved evidence count: {typeof trace.retrieved_evidence_count==='number'?trace.retrieved_evidence_count:'Not provided'}</p>{Array.isArray(trace.tool_decisions) && <ol>{trace.tool_decisions.map((d,i)=><li key={i}>{d.tool}: {d.reason}</li>)}</ol>}<h4>Retrieval checks</h4>{Array.isArray(trace.retrieval_checks) && trace.retrieval_checks.length?<pre>{JSON.stringify(trace.retrieval_checks,null,2)}</pre>:<p>No retrieval checks reported.</p>}<h4>Tool executions</h4>{Array.isArray(trace.tool_executions) && trace.tool_executions.length?<pre>{JSON.stringify(trace.tool_executions,null,2)}</pre>:<p>No tool executions reported.</p>}</>:<p>Execution trace unavailable.</p>}</details></>}
 {tab==='Sources' && <><h3>Cited source documents</h3>{response?.sources.length?<ul className="inspector-citations">{response.sources.map(source=><li key={source}>{source}</li>)}</ul>:<p className="unavailable">No cited sources for the active response.</p>}<h3>Returned evidence</h3><p className="inspector-note">Verbatim API provenance, not full documents. Retrieved chunks on a refusal are not supporting citations. Scores are retrieval signals, not confidence.</p>{response?.provenance.length?response.provenance.map((e,i)=><details className="inspector-source" key={`${e.chunk_id}-${i}`}><summary>#{e.rank} · {e.source_document}<small>{e.section}</small></summary><p className="verbatim">{e.text}</p><dl><dt>Chunk ID</dt><dd>{e.chunk_id}</dd><dt>Retrieval score</dt><dd>{e.score}</dd><dt>Selection reason</dt><dd>{e.selection_reason || 'Not provided'}</dd></dl></details>):<p className="unavailable">No evidence returned.</p>}</>}
 {tab==='Knowledge Graph' && <><h3>Answer-specific retrieved relationships</h3><p className="inspector-note">Only explicit relationship metadata returned with this response is displayed. These are corpus-extracted relationships, not verified generated claims.{response && !response.evidence_sufficient?' The response refused; these edges are retrieval context, not support for an answer.':''}</p>{edges.length?edges.map((e,i)=><div className="relationship-card" key={`${e.chunk_id}-${i}`}><div className="graph-pair"><span>{e.entity_path[0]}</span><span className="graph-arrow">{e.relationship_type} →</span><span>{e.entity_path[1]}</span></div><p>{e.source_document} · {e.section}</p><small>Evidence chunk: {e.chunk_id}</small><details><summary>Source evidence</summary><p className="verbatim">{e.text}</p></details></div>):<p className="unavailable">No explicit graph relationships in this response. This does not mean the corpus has no relationships; hybrid or semantic provenance may not expose edges.</p>}<h3>Corpus overview</h3><CorpusGraph/></>}
 </div><p className="inspector-footer">Synthetic corpus · No confidence percentages or approval guarantees.</p></aside>;
}
