import {useEffect,useRef,useState} from 'react';
import AnswerInspector from './AnswerInspector';
import {ApiError,newSession,queryApi,type QueryResponse} from './api';
const examples=[['Deployment','According to the deployment guide, what are the steps to deploy the application?'],['Architecture','How does the API Gateway interact with the OCR Service?'],['Security','Which teams own platform operations and security?'],['Incidents','What caused the batch processing incident?']];
type Turn={question:string;response?:QueryResponse;error?:string;requestId?:string|null};
type Conversation={id:string;sessionId:string;lastActive:number;turns:Turn[];draft:string};
const createConversation=():Conversation=>({id:newSession(),sessionId:newSession(),lastActive:0,turns:[],draft:''});
export default function App(){
 const [conversations,setConversations]=useState<Conversation[]>(()=>[createConversation()]);
 const [activeId,setActiveId]=useState<string|null>(null);
 const active=conversations.find(c=>c.id===activeId) || conversations[0];
 const question=active.draft; const turns=active.turns;
 const [busy,setBusy]=useState(false); const [slow,setSlow]=useState(false);
 const request=useRef<AbortController|null>(null); const input=useRef<HTMLTextAreaElement>(null);
 function update(id:string,fn:(c:Conversation)=>Conversation){setConversations(old=>old.map(c=>c.id===id?fn(c):c));}
 function setQuestion(draft:string){update(active.id,c=>({...c,draft}));}
 useEffect(()=>()=>request.current?.abort(),[]);
 useEffect(()=>{if(!busy){setSlow(false);return;}const t=setTimeout(()=>setSlow(true),8000);return()=>clearTimeout(t);},[busy]);
 async function submit(event:React.FormEvent){event.preventDefault();const q=question.trim();if(!q || q.length>2000 || request.current)return;
 const id=active.id;const sessionId=active.lastActive && Date.now()-active.lastActive>=1800000?newSession():active.sessionId;
 const controller=new AbortController();request.current=controller;setBusy(true);update(id,c=>({...c,sessionId,draft:'',turns:[...c.turns,{question:q}]}));
 const timer=setTimeout(()=>controller.abort(),90000);
 try {const response=await queryApi(q,sessionId,controller.signal);update(id,c=>({...c,sessionId:response.session_id,lastActive:Date.now(),turns:c.turns.map((t,i)=>i===c.turns.length-1?{...t,response}:t)}));}
 catch(error){const e=error instanceof ApiError?error:null;update(id,c=>({...c,draft:q,turns:c.turns.map((t,i)=>i===c.turns.length-1?{...t,error:e?.message || 'The request timed out. Render Free may be waking up. Please retry; no answer was received.',requestId:e?.requestId}:t)}));}
 finally{clearTimeout(timer);request.current=null;setBusy(false);}
 }
 function reset(){if(request.current)return;const fresh=createConversation();setConversations(old=>[fresh,...old.filter(c=>c.turns.length || c.draft)].slice(0,20));setActiveId(fresh.id);input.current?.focus();}
 function switchConversation(id:string){if(request.current)return;setActiveId(id);input.current?.focus();}
 return <div className={`shell ${turns.length ? 'has-conversation' : ''}`}><aside className="sidebar"><a href="#workspace" className="brand"><span className="brand-mark">K</span><span>Knowledge<br/><strong>Copilot</strong></span></a><div className="sidebar-label">WORKSPACE</div><div className="nav-active">◈ &nbsp; Ask your knowledge</div><nav className="conversation-nav" aria-label="Client-side conversations"><div className="sidebar-label">CONVERSATIONS</div><p className="history-note">This tab only · not server history</p><div className="conversation-links">{conversations.map(c=><button key={c.id} disabled={busy} aria-current={c.id===active.id?'page':undefined} onClick={()=>switchConversation(c.id)} title={c.turns[0]?.question || 'Untitled conversation'}><span aria-hidden="true">◌</span><span>{c.turns[0]?.question || 'Untitled conversation'}</span></button>)}</div></nav><div className="sidebar-note"><span className="eyebrow">THE DEMO CORPUS</span><h2>Enterprise context.<br/>Inspectable evidence.</h2><p>Eight synthetic documents covering an OCR platform, release workflows, security, and operations.</p><div className="doc-tags"><span>Architecture</span><span>Deployment</span><span>Security</span><span>Incidents</span></div></div><div className="sidebar-footer">PORTFOLIO DEMO<br/><span>Synthetic documents · No uploads</span></div></aside>
 <main id="workspace"><header className="topbar"><span>Enterprise Knowledge Copilot <span className="version">/ DEMO</span></span><button onClick={reset} disabled={busy} className="quiet-button">New conversation ↗</button></header>
 <div className="workspace"><div className="intro"><span className="eyebrow">FROM QUESTION TO EVIDENCE</span><h1>Your knowledge, <span>with context.</span></h1><p>Ask about the demo platform. Explore the answer and the source text behind it.</p></div>
 <form onSubmit={submit} className="composer"><label htmlFor="question">What would you like to know?</label><textarea ref={input} id="question" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={2000} rows={2} placeholder="Ask a question about deployment, architecture, or operations…" aria-describedby="input-help" disabled={busy}/><div className="composer-bottom"><span id="input-help">{question.length.toLocaleString()} / 2,000 · Follow-up questions supported</span><button type="submit" className="ask-button" disabled={busy || !question.trim()}>{busy?'Searching…':'Ask Copilot'} <span aria-hidden="true">↗</span></button></div></form>
 <div className="examples"><span>EXPLORE A WORKFLOW</span><div>{examples.map(([label,q])=><button key={label} disabled={busy} onClick={()=>{setQuestion(q);input.current?.focus();}}>{label} <span aria-hidden="true">↗</span></button>)}</div></div>
 <section className="conversation" aria-label="Conversation" aria-busy={busy}>{!turns.length?<div className="empty"><span className="empty-icon" aria-hidden="true">◈</span><h2>Answers you can inspect</h2><p>Every response includes its grounding decision.<br/>When evidence is insufficient, the Copilot says so.</p><div className="empty-features"><span>01 &nbsp; Ask a question</span><span>02 &nbsp; Read the answer</span><span>03 &nbsp; Inspect evidence</span></div></div>:[...turns].reverse().map((turn,i)=><article key={`${active.id}-${turns.length-1-i}`} className="turn"><div className="user-question"><span className="avatar user-avatar" aria-hidden="true">Y</span><div><span className="speaker">YOU</span><p>{turn.question}</p></div></div><div className="assistant-response"><span className="avatar ai-avatar" aria-hidden="true">K</span><div className="response-body"><div className="response-heading"><span className="speaker">KNOWLEDGE COPILOT</span>{turn.response && <span className={`status ${turn.response.evidence_sufficient?'grounded':'insufficient'}`}>{turn.response.evidence_sufficient?'● Grounded':'○ Insufficient evidence'}</span>}</div>
 {turn.error?<div role="alert" className="error"><p>{turn.error}</p>{turn.requestId && <small>Request ID: {turn.requestId}</small>}<button className="quiet-button" onClick={()=>{setQuestion(turn.question);input.current?.focus();}} disabled={busy}>Edit and retry ↗</button></div>:turn.response?<><p className="answer">{turn.response.answer}</p><p className="support-reason">{turn.response.sufficiency_reason}</p><div className="source-list" aria-label="Cited source documents">{turn.response.sources.length?turn.response.sources.map(source=><span key={source}>▤ &nbsp; {source}</span>):<span>No sources cited</span>}</div><details className="evidence"><summary>Inspect {turn.response.provenance.length} evidence chunks <span>↓</span></summary><p className="evidence-note">Retrieved provenance is shown verbatim. On a refusal these chunks are not claimed as supporting citations. Scores are retrieval signals, not confidence.</p>{turn.response.provenance.map((e,j)=><div className="evidence-chunk" key={`${e.chunk_id}-${j}`}><div><strong>#{e.rank} · {e.source_document}</strong><span>Score {e.score.toFixed(3)}</span></div><h3>{e.section}</h3><p>{e.text}</p><small>Chunk: {e.chunk_id}</small></div>)}</details></>:<div role="status" className="loading"><span className="pulse"/> {slow?'The API may be waking up on Render Free. This can take up to a minute.':'Searching the corpus and checking support…'}</div>}
 </div></div></article>)}</section><footer className="disclaimer">Synthetic-document portfolio demo. Not a production enterprise deployment. Grounding is determined by deterministic checks; verify the source evidence. Render Free can sleep and conversation context may reset after 30 minutes, eviction, or a service restart.</footer></div></main><AnswerInspector key={active.id} response={turns.at(-1)?.response} question={turns.at(-1)?.question} pending={busy}/></div>;
}
